#macro RIGHT 0
#macro UP 1
#macro LEFT 2
#macro DOWN 3
#macro IDLE_RIGHT 4
#macro IDLE_UP 5
#macro IDLE_LEFT 6
#macro IDLE_DOWN 7
#macro NW 8
#macro NE 9
#macro SW 10
#macro SE 11
#macro IDLE_NW 12
#macro IDLE_NE 13
#macro IDLE_SW 14
#macro IDLE_SE 15